(function(){
var h=false,j=null,m=true,n=(new Date).getTime();function aa(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c}function o(a,b){var c=/^([\w-]+\.)+[\w-]{2,}(\:[0-9]+)?$/;return c.test(a)?a:b};var ba="pagead2.googlesyndication.com",ca="googleads.g.doubleclick.net",da="partner.googleadservices.com",ea=o("pagead2.googlesyndication.com",ba),fa=o("googleads.g.doubleclick.net",ca),ga=o("pagead2.googlesyndication.com",ba),ha=o("partner.googleadservices.com",da);var ia={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",
google_gl:"gl",google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},ma={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_analytics_uacct:"ga_wpids",google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",
google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},na={google_only_pyv_ads:"pyv"};function p(a){return ia[a]||ma[a]||na[a]||j};document.URL.indexOf("?google_debug")>0||document.URL.indexOf("&google_debug")>0;function q(){this.b=this.p();this.h=h;if(!this.b)this.h=this.j()}q.prototype.f="__gads=";q.prototype.c="GoogleAdServingTest=";q.prototype.o=function(){return this.b};q.prototype.setCookieInfo=function(a){this.a=a._cookies_[0];if(this.a!=j){this.b=this.a._value_;this.q()}};q.prototype.l=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};var oa="http://"+ha+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo";
q.prototype.k=function(a){if(!(this.b||!this.h)){var b="script",c=document.domain,d=oa+"&client="+r(a)+"&domain="+r(c);document.write("<"+b+' src="'+d+'"></'+b+">")}};q.prototype.j=function(){document.cookie=this.c+"Good";var a=this.g(this.c),b=a=="Good";if(b){var c=this.l(-1);document.cookie=this.c+"; expires="+c.toGMTString()}return b};q.prototype.p=function(){var a=this.g(this.f);return a};
q.prototype.g=function(a){var b=document.cookie,c=b.indexOf(a),d="";if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};q.prototype.q=function(){if(!(this.a==j))if(!!this.b){var a=new Date;a.setTime(1000*this.a._expires_);var b=this.a._domain_,c=this.f+this.b+"; expires="+a.toGMTString()+"; path="+this.a._path_+"; domain=."+b;document.cookie=c}};
function pa(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){for(var b=3,c=1;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=j}return b.toString()}else if(qa()){var c=j;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(e){var b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
b=6;c.AllowScriptAccess="always"}catch(f){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(g){}}if(c){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"};function ra(a,b,c,d){var e=c||a.google_ad_width,f=d||a.google_ad_height;if(a.top.location==b.location)return h;var g=b.documentElement;if(e&&f){var i=1,l=1;if(a.innerHeight){i=a.innerWidth;l=a.innerHeight}else if(g&&g.clientHeight){i=g.clientWidth;l=g.clientHeight}else if(b.body){i=b.body.clientWidth;l=b.body.clientHeight}if(l>2*f||i>2*e)return h}return m}function sa(a,b){for(var c in b)a["google_"+c]=b[c]}function ta(a,b){if(!b)return a.location;return a.referrer}
function ua(a,b){if(!b&&a.google_referrer_url==j)return"0";else if(b&&a.google_referrer_url==j)return"1";else if(!b&&a.google_referrer_url!=j)return"2";else if(b&&a.google_referrer_url!=j)return"3";return"4"}function va(a,b,c,d){a.page_url=ta(c,d);a.page_location=j}function wa(a,b,c,d){a.page_url=b.google_page_url;a.page_location=ta(c,d)||"EMPTY"}
function xa(a,b){var c={},d=ra(a,b,a.google_ad_width,a.google_ad_height);c.iframing=ua(a,d);!!a.google_page_url?wa(c,a,b,d):va(c,a,b,d);c.last_modified_time=b.location==c.page_url?Date.parse(b.lastModified)/1000:j;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}
function ya(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=j;b.page_url=c;b.page_location=a.location;b.last_modified_time=j;b.referrer_url=c;return b}function za(a,b){var c=Aa(a,b);sa(a,c)}function Aa(a,b){var c;return c=a.google_page_url==j&&Ba[b.domain]?ya(b):xa(a,b)}var Ba={};Ba["ad.yieldmanager.com"]=m;var u=this,x=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]")return"array";if(typeof a.call!="undefined")return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b};var Ca=function(a){var b=x(a);return b=="array"||b=="object"&&typeof a.length=="number"};
var Da=function(a){var b=x(a);return b=="object"||b=="array"||b=="function"},Ea=function(a){var b=x(a);if(b=="object"||b=="array"){if(a.clone)return a.clone.call(a);var c=b=="array"?[]:{};for(var d in a)c[d]=Ea(a[d]);return c}return a},Fa=Date.now||function(){return(new Date).getTime()};var Ga=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else for(var d=a.length,e=typeof a=="string"?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ha=function(a){if(x(a)=="array")return a.concat();else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var y=function(a,b){this.x=typeof a!="undefined"?a:0;this.y=typeof b!="undefined"?b:0};y.prototype.clone=function(){return new y(this.x,this.y)};y.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var z=function(a,b){this.width=a;this.height=b};z.prototype.clone=function(){return new z(this.width,this.height)};z.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};z.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};z.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
z.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};z.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Ia=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var Ja=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Pa=function(a,b){if(b)return a.replace(Ka,"&amp;").replace(La,"&lt;").replace(Ma,"&gt;").replace(Na,"&quot;");else{if(!Oa.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(Ka,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(La,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(Ma,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(Na,"&quot;");return a}},Ka=/&/g,La=/</g,Ma=/>/g,Na=/\"/g,Oa=/[&<>\"]/,Qa=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=c==
1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a};
var Ra=function(a,b){for(var c=0,d=Ja(String(a)).split("."),e=Ja(String(b)).split("."),f=Math.max(d.length,e.length),g=0;c==0&&g<f;g++){var i=d[g]||"",l=e[g]||"",k=new RegExp("(\\d*)(\\D*)","g"),A=new RegExp("(\\d*)(\\D*)","g");do{var v=k.exec(i)||["","",""],w=A.exec(l)||["","",""];if(v[0].length==0&&w[0].length==0)break;var s=v[1].length==0?0:parseInt(v[1],10),G=w[1].length==0?0:parseInt(w[1],10);c=B(s,G)||B(v[2].length==0,w[2].length==0)||B(v[2],w[2])}while(c==0)}return c},B=function(a,b){if(a<
b)return-1;else if(a>b)return 1;return 0};Fa();var C,D,E,Sa,Ta,Ua,Va,Wa,Xa,Ya=function(){return u.navigator?u.navigator.userAgent:j};var Za=function(){Ua=Ta=Sa=E=D=C=h;var a;if(a=Ya()){var b=u.navigator;C=a.indexOf("Opera")==0;D=!C&&a.indexOf("MSIE")!=-1;Sa=(E=!C&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;Ua=(Ta=!C&&!E&&b.product=="Gecko")&&b.vendor=="Camino"}};Za();
var F=C,H=D,I=Ta,J=E,$a=Sa,ab=function(){var a=u.navigator;return a&&a.platform||""},cb=ab(),fb=function(){Va=cb.indexOf("Mac")!=-1;Wa=cb.indexOf("Win")!=-1;Xa=cb.indexOf("Linux")!=-1};fb();var gb=Va,hb=Wa,ib=Xa,jb=function(){var a="",b;if(F&&u.opera){var c=u.opera.version;a=typeof c=="function"?c():c}else{if(I)b=/rv\:([^\);]+)(\)|;)/;else if(H)b=/MSIE\s+([^\);]+)(\)|;)/;else if(J)b=/WebKit\/(\S+)/;if(b){var d=b.exec(Ya());a=d?d[1]:""}}return a},kb=jb();
var lb={},K=function(a){return lb[a]||(lb[a]=Ra(kb,a)>=0)};var L;var mb=function(a){return a?new M(N(a)):L||(L=new M)};
var nb=function(a){return typeof a=="string"?document.getElementById(a):a},ob=nb,qb=function(a,b){Ia(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in pb)a.setAttribute(pb[d],c);else a[d]=c})},pb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"},rb=function(a){var b=a||u||window,c=b.document;
if(J&&!K("500")&&!$a){if(typeof b.innerHeight=="undefined")b=window;var d=b.innerHeight,e=b.document.documentElement.scrollHeight;if(b==b.top)if(e<d)d-=15;return new z(b.innerWidth,d)}var f=mb(c),g=f.e()&&(!F||F&&K("9.50"))?c.documentElement:c.body;return new z(g.clientWidth,g.clientHeight)},sb=function(){var a=L||(L=new M);return a.i.apply(a,arguments)},tb=function(a,b){a.appendChild(b)},ub=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):j},vb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,
b)};
var wb=J&&Ra(kb,"521")<=0,xb=function(a,b){if(typeof a.contains!="undefined"&&!wb&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},N=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},yb=function(a){if(a&&typeof a.length=="number")if(Da(a))return typeof a.item=="function"||typeof a.item=="string";else if(x(a)=="function")return typeof a.item=="function";return h},
M=function(a){this.d=a||u.document||document};
M.prototype.i=function(a,b){if(H&&b&&(b.name||b.type)){var c=["<",a];b.name&&c.push(' name="',Pa(b.name),'"');if(b.type){c.push(' type="',Pa(b.type),'"');b=Ea(b);delete b.type}c.push(">");a=c.join("")}var d=this.createElement(a);b&&qb(d,b);if(arguments.length>2){function e(i){if(i)this.appendChild(d,typeof i=="string"?this.createTextNode(i):i)}for(var f=2;f<arguments.length;f++){var g=arguments[f];Ca(g)&&!(Da(g)&&g.nodeType>0)?Ga(yb(g)?Ha(g):g,e,this):e.call(this,g)}}return d};
M.prototype.createElement=function(a){return this.d.createElement(a)};M.prototype.createTextNode=function(a){return this.d.createTextNode(a)};M.prototype.e=function(){var a=this.d;if(a.compatMode)return a.compatMode=="CSS1Compat";if(J){var b=a.createElement("div");b.style.cssText="position:absolute;width:0;height:0;width:1";var c=b.style.width=="1px"?"BackCompat":"CSS1Compat";return(a.compatMode=c)=="CSS1Compat"}return h};
M.prototype.n=function(){var a=this.d;return!J&&this.e()?a.documentElement:a.body};M.prototype.m=function(){var a=this.n();return new y(a.scrollLeft,a.scrollTop)};M.prototype.appendChild=tb;M.prototype.removeNode=ub;M.prototype.replaceNode=vb;M.prototype.contains=xb;var zb,Ab,Bb,Cb,Db,Eb,Fb=function(){Eb=Db=Cb=Bb=Ab=zb=h;var a=Ya();if(!!a)if(a.indexOf("Firefox")!=-1)zb=m;else if(a.indexOf("Camino")!=-1)Ab=m;else if(a.indexOf("iPhone")!=-1||a.indexOf("iPod")!=-1)Bb=m;else if(a.indexOf("Android")!=-1)Cb=m;else if(a.indexOf("Chrome")!=-1)Db=m;else if(a.indexOf("Safari")!=-1)Eb=m};Fb();var Gb=function(a,b){var c=N(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return j};var O=function(a,b){return Gb(a,b)||(a.currentStyle?a.currentStyle[b]:j)||a.style[b]};
var Hb=function(a){var b;b=a?a.nodeType==9?a:N(a):document;if(H&&!mb(b).e())return b.body;return b.documentElement},Ib=function(a){var b=a.getBoundingClientRect();if(H){var c=a.ownerDocument;b.left-=c.documentElement.clientLeft+c.body.clientLeft;b.top-=c.documentElement.clientTop+c.body.clientTop}return b},Jb=function(a){if(H)return a.offsetParent;for(var b=N(a),c=O(a,"position"),d=c=="fixed"||c=="absolute",e=a.parentNode;e&&e!=b;e=e.parentNode){c=O(e,"position");d=d&&c=="static"&&e!=b.documentElement&&
e!=b.body;if(!d&&(e.scrollWidth>e.clientWidth||e.scrollHeight>e.clientHeight||c=="fixed"||c=="absolute"))return e}return j},Kb=function(a){var b,c=N(a),d=O(a,"position"),e=I&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),f=new y(0,0),g=Hb(c);if(a==g)return f;if(a.getBoundingClientRect){b=Ib(a);var i=mb(c).m();f.x=b.left+i.x;f.y=b.top+i.y}else if(c.getBoxObjectFor&&!e){b=c.getBoxObjectFor(a);var l=c.getBoxObjectFor(g);f.x=b.screenX-
l.screenX;f.y=b.screenY-l.screenY}else{var k=a;do{f.x+=k.offsetLeft;f.y+=k.offsetTop;if(k!=a){f.x+=k.clientLeft||0;f.y+=k.clientTop||0}if(J&&O(k,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}k=k.offsetParent}while(k&&k!=a);if(F||J&&d=="absolute")f.y-=c.body.offsetTop;for(k=a;(k=Jb(k))&&k!=c.body;){f.x-=k.scrollLeft;if(!F||k.tagName!="TR")f.y-=k.scrollTop}}return f};I&&K("1.9");
var Lb=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);else{var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;var g=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return g}},Mb=function(a){var b=N(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=O(a,"fontFamily");if(F&&ib)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return Qa(c,"\"'")},Nb=function(a){var b=
a.match(/[^\d]+$/);return b&&b[0]||j},Ob={cm:1,"in":1,mm:1,pc:1,pt:1},Pb={em:1,ex:1},Qb=function(a){var b=O(a,"fontSize"),c=Nb(b);if(b&&"px"==c)return parseInt(b,10);if(H)if(c in Ob)return Lb(a,b,"left","pixelLeft");else if(a.parentNode&&a.parentNode.nodeType==1&&c in Pb){var d=a.parentNode,e=O(d,"fontSize");return Lb(d,b==e?"1em":b,"left","pixelLeft")}var f=sb("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});tb(a,f);b=f.offsetHeight;ub(f);
return b};var P=document,Q=navigator,R=window;
function Rb(){var a=P.cookie,b=Math.round((new Date).getTime()/1000),c=R.google_analytics_domain_name,d=typeof c=="undefined"?Sb("auto"):Sb(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,g=a.indexOf("__utmc="+d)>-1,i,l={};if(e){i=a.split("__utma="+d+".")[1].split(";")[0].split(".");l.sid=f&&g?i[3]+"":R&&R.gaGlobal&&R.gaGlobal.sid?R.gaGlobal.sid:b+"";l.vid=i[0]+"."+i[1];l.from_cookie=m}else{l.sid=R&&R.gaGlobal&&R.gaGlobal.sid?R.gaGlobal.sid:b+"";l.vid=R&&R.gaGlobal&&R.gaGlobal.vid?
R.gaGlobal.vid:(Tb()^Ub()&2147483647)+"."+b;l.from_cookie=h}l.dh=d;l.hid=R&&R.gaGlobal&&R.gaGlobal.hid?R.gaGlobal.hid:Tb();return R.gaGlobal=l}function Tb(){return Math.round(Math.random()*2147483647)}
function Ub(){var a=P.cookie?P.cookie:"",b=R.history.length,c,d,e=[Q.appName,Q.version,Q.language?Q.language:Q.browserLanguage,Q.platform,Q.userAgent,Q.javaEnabled()?1:0].join("");if(R.screen)e+=R.screen.width+"x"+R.screen.height+R.screen.colorDepth;else if(R.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=P.referrer?P.referrer:"";for(c=e.length;b>0;)e+=b--^c++;return Vb(e)}
function Vb(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Sb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=P.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Vb(a.toLowerCase())};var S="";function Wb(a){if(a){if(S!="")S+=",";S+=a}}var Xb=h;function Yb(a,b){var c="script";(Xb=Zb(a,b))||(a.google_allow_expandable_ads=h);var d=!$b();Xb&&d&&b.write("<"+c+' src="http://'+ea+'/pagead/expansion_embed.js"></'+c+">");var e=ac(a,b,aa("1",0.01)),f=d||e;f&&qa()?b.write("<"+c+' src="http://'+ea+'/pagead/render_ads.js"></'+c+">"):b.write("<"+c+">window.google_render_ad();</"+c+">")}function T(a){return a!=j?'"'+a+'"':'""'}
function r(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function U(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}function V(a){var b=window,c=p(a),d=b[a];U(c,d)}function W(a,b){b!=j&&U(a,r(b))}function X(a){var b=window,c=p(a),d=b[a];W(c,d)}function Y(a,b){var c=window,d=p(a),e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];U(d,e)}
function bc(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){U("u_h",b.height);U("u_w",b.width);U("u_ah",b.availHeight);U("u_aw",b.availWidth);U("u_cd",b.colorDepth)}U("u_tz",d);U("u_his",history.length);U("u_java",c);navigator.plugins&&U("u_nplug",navigator.plugins.length);navigator.mimeTypes&&U("u_nmime",navigator.mimeTypes.length)}
function cc(a){if(!!a.google_enable_first_party_cookie){if(a._GA_googleCookieHelper==j)a._GA_googleCookieHelper=new q;if(!a._google_cookie_fetched){a._google_cookie_fetched=m;a._GA_googleCookieHelper.k(dc(a.google_ad_client))}}}function dc(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function ec(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}function fc(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}
function gc(){var a=H&&K("6")&&!K("8"),b=I&&K("1.8.1"),c=J&&K("525");if(hb&&(a||b||c))return m;else if(gb&&(c||b))return m;else if(ib&&b)return m;return h}function $b(){return typeof ExpandableAdSlotFactory=="function"&&typeof ExpandableAdSlotFactory.createIframe=="function"}function Zb(a,b){if(a.google_allow_expandable_ads===h||!b.body||a.google_ad_output!="html"||ra(a,b)||hc(a)||Z(a.google_ad_format)||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||!gc())return h;return m}
function ic(){var a=Math.random(),b=aa("0.01",0);if(a<b)return"68120011";if(a<2*b)return"68120021";if(a<3*b)return"68120031";if(a<4*b)return"68120041";return""}
function jc(a,b,c,d){var e=fc(a);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+T($(c))+"></"+f+">");else if(a.google_ad_output=="html")if(Xb&&$b()){var g=a.google_container_id||d||j;a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe("google_ads_frame"+e,$(c),a.google_ad_width,a.google_ad_height,g)}else{var i=
'<iframe name="google_ads_frame" width='+T(a.google_ad_width)+" height="+T(a.google_ad_height)+" frameborder="+T(a.google_ad_frameborder)+" src="+T($(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';a.google_container_id?kc(a.google_container_id,b,i):b.write(i)}else a.google_ad_output=="textlink"&&b.write("<"+f+' language="JavaScript1.1" src='+T($(c))+"></"+f+">")}function lc(a,b,c){if(!a)return h;if(!b)return m;return c}
function mc(a){for(var b in ia)a[b]=j;for(var b in ma)b=="google_correlator"||(a[b]=j);for(var b in na)a[b]=j;a.google_allow_expandable_ads=j;a.google_container_id=j;a.google_tag_info=j}function hc(a){if(a.google_ad_format)return a.google_ad_format.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function Z(a){return a&&a.indexOf("_sdo")!=-1}
function nc(a,b){var c=j,d=window,e=document,f=n,g=d.google_ad_format,i=oc(d),l;if(d.google_cpa_choice!=c){d.google_ad_url=i+"/cpa/ads?";l=escape(dc(d.google_ad_client));d.google_ad_region="_google_cpa_region_";V("google_cpa_choice");if(typeof e.characterSet!="undefined")W("oe",e.characterSet);else typeof e.charset!="undefined"&&W("oe",e.charset)}else if(Z(g)){d.google_ad_url=i+"/pagead/sdo?";l=escape(ec(d.google_ad_client))}else{d.google_ad_url=i+"/pagead/ads?";l=escape(dc(d.google_ad_client))}d.google_ad_url+=
"client="+l;V("google_ad_host");V("google_ad_host_tier_id");var k=d.google_num_slots_by_client,A=d.google_num_slots_by_channel,v=d.google_prev_ad_formats_by_region,w=d.google_prev_ad_slotnames_by_region;if(d.google_ad_region==c&&d.google_ad_section!=c)d.google_ad_region=d.google_ad_section;var s=d.google_ad_region==c?"":d.google_ad_region;if(Z(g)){d.google_num_sdo_slots=d.google_num_sdo_slots?d.google_num_sdo_slots+1:1;if(d.google_num_sdo_slots>4)return h}else if(hc(d)){d.google_num_0ad_slots=d.google_num_0ad_slots?
d.google_num_0ad_slots+1:1;if(d.google_num_0ad_slots>3)return h}else if(d.google_cpa_choice==c){d.google_num_ad_slots=d.google_num_ad_slots?d.google_num_ad_slots+1:1;if(d.google_num_slots_to_rotate){v[s]=c;w[s]=c;if(d.google_num_slot_to_show==c)d.google_num_slot_to_show=f%d.google_num_slots_to_rotate+1;if(d.google_num_slot_to_show!=d.google_num_ad_slots)return h}else if(d.google_num_ad_slots>6&&s=="")return h}U("dt",n);V("google_language");d.google_country?V("google_country"):V("google_gl");V("google_region");
X("google_city");X("google_hints");V("google_safe");V("google_encoding");V("google_last_modified_time");X("google_alternate_ad_url");V("google_alternate_color");V("google_skip");V("google_targeting");var G=d.google_ad_client;if(k[G])k[G]+=1;else{k[G]=1;k.length+=1}if(v[s])if(!Z(g)){W("prev_fmts",v[s].toLowerCase());k.length>1&&U("slot",k[G])}w[s]&&W("prev_slotnames",w[s].toLowerCase());if(lc(g,d.google_ad_slot,d.google_override_format)){W("format",g.toLowerCase());Z(g)||(v[s]=v[s]?v[s]+","+g:g)}else if(d.google_ad_slot)w[s]=
w[s]?w[s]+","+d.google_ad_slot:d.google_ad_slot;V("google_max_num_ads");U("output",d.google_ad_output);V("google_adtest");V("google_ad_callback");V("google_ad_slot");X("google_correlator");d.google_new_domain_checked==1&&d.google_new_domain_enabled==0&&U("dblk",1);if(d.google_ad_channel){X("google_ad_channel");for(var bb="",db=d.google_ad_channel.split(pc),ja=0;ja<db.length;ja++){var ka=db[ja];if(A[ka])bb+=ka+"+";else A[ka]=1}W("pv_ch",bb)}if(d.google_ad_host_channel){X("google_ad_host_channel");
var vc=qc(d.google_ad_host_channel,d.google_viewed_host_channels);W("pv_h_ch",vc)}d.google_enable_first_party_cookie&&W("cookie",d._GA_googleCookieHelper.o());X("google_page_url");Y("google_color_bg",f);Y("google_color_text",f);Y("google_color_link",f);Y("google_color_url",f);Y("google_color_border",f);Y("google_color_line",f);d.google_reuse_colors?U("reuse_colors",1):U("reuse_colors",0);V("google_font_face");V("google_kw_type");X("google_kw");X("google_contents");V("google_num_radlinks");V("google_max_radlink_len");
V("google_rl_filtering");V("google_rl_mode");V("google_rt");X("google_rl_dest_url");V("google_num_radlinks_per_unit");V("google_ad_type");V("google_image_size");V("google_ad_region");W("eid",S);var eb=d.google_allow_expandable_ads;if(eb!=j)eb?U("ea","1"):U("ea","0");V("google_feedback");X("google_referrer_url");X("google_page_location");U("frm",d.google_iframing);V("google_bid");V("google_ctr_threshold");V("google_cust_age");V("google_cust_gender");V("google_cust_interests");V("google_cust_id");V("google_cust_job");
V("google_cust_u_url");V("google_cust_l");V("google_cust_lh");V("google_cust_ch");V("google_ed");V("google_video_doc_id");V("google_video_product_type");X("google_ui_features");X("google_ui_version");X("google_tag_info");X("google_only_ads_with_video");X("google_only_pyv_ads");X("google_disable_video_autoplay");if(a){W("ff",Mb(a));W("fs",Qb(a));var t;if(b)if(typeof a.getBoundingClientRect=="function"){t=a.getBoundingClientRect();t.x=t.left;t.y=t.top}else{t={};t.x="-252738";t.y="-252738"}else try{t=
Kb(a)}catch(Bc){t={};t.x="-252738";t.y="-252738"}var la=rb();if(t&&la){W("biw",la.width);W("bih",la.height);W("adx",t.x);W("ady",t.y)}}Rb();U("ga_vid",d.gaGlobal.vid);U("ga_sid",d.gaGlobal.sid);U("ga_hid",d.gaGlobal.hid);U("ga_fc",d.gaGlobal.from_cookie);X("google_analytics_uacct");V("google_ad_override");V("google_flash_version");bc(d);return m}
function qc(a,b){for(var c=a.split("|"),d=-1,e=[],f=0;f<c.length;f++){var g=c[f].split(pc);b[f]||(b[f]={});for(var i="",l=0;l<g.length;l++){var k=g[l];if(!(k==""))if(b[f][k])i+="+"+k;else b[f][k]=1}i=i.slice(1);e[f]=i;if(i!="")d=f}var A="";if(d>-1){for(var f=0;f<d;f++)A+=e[f]+"|";A+=e[d]}return A}
function rc(){var a=window,b=document;cc(a);var c=ic();Wb(c);var d,e=h,f=h,g=h;switch(c){case "68120031":g=m;case "68120021":f=m;case "68120041":e=m}if(e){var i="google_temp_span";d=a.google_container_id&&ob(a.google_container_id)||ob(i);if(!d&&!a.google_container_id){b.write("<span id="+i+"></span>");d=ob(i)}}var l=nc(f&&d,g);d&&d.id==i&&ub(d);if(!!l){jc(a,b,a.google_ad_url);mc(a)}}function $(a){var b=(new Date).getTime()-n,c="&dtd="+(b<1000?b:"M");return a+c}function sc(){rc();return m}
function tc(a){var b=window,c=j,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if(Z(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html")b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;za(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=n;if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot={};if(b.google_flash_version==
c)b.google_flash_version=pa();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function uc(a){if(a in wc)return wc[a];return wc[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var wc={};function qa(){return uc("msie")&&!window.opera}
function xc(a){for(var b={},c=a.split("?"),d=c[c.length-1].split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(g){}}return b}function yc(){var a=window,b=xc(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}
function kc(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var pc=/[+, ]/;window.google_render_ad=rc;var zc={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1};function Ac(a){var b=a.google_page_location||a.google_page_url;if(!b)return h;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=h;if(e.length>=3)f=e[e.length-3]in zc;if(e.length>=2)f=f||e[e.length-2]in zc;return f}
function ac(a,b,c){if(Ac(a)){a.google_new_domain_checked=1;return h}if(a.google_new_domain_checked==0){var d=Math.random();if(d<=c){var e="http://"+fa+"/pagead/test_domain.js",f="script";b.write("<"+f+' src="'+e+'"></'+f+">");a.google_new_domain_checked=1;return m}}return h}function oc(a){if(!Ac(a)&&a.google_new_domain_enabled==1)return"http://"+fa;return"http://"+ga};yc();tc(sc);Yb(window,document);
})()
